name: Release for multiple platforms

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [mipsle]
        gomips: [softfloat]
    steps:
    - uses: actions/checkout@v4

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}

    - name: Set ldflags as environment variable
      run: |
        LD_FLAGS="-X main.Version=${{ env.APP_VERSION }}"
        echo "LD_FLAGS=$LD_FLAGS" >> ${GITHUB_ENV}
        echo "CGO_ENABLED=0" >> ${GITHUB_ENV}
        echo "GOMIPS=softfloat" >> ${GITHUB_ENV}

    - uses: pdahd/go-release-action@v0.1-test-assets
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goarm: ${{ matrix.goarm }}
        gomips: ${{ matrix.gomips }}
        project_path: "."
        binary_name: "CloudflareWarpSpeedTest"
        goversion: "1.22"
        ldflags: "${{ env.LD_FLAGS }}"
